export const ROUNDS = [
  { id:'sjt', name:'Situational Judgement', icon:'🎭', desc:'17 real-world workplace scenarios in 10 minutes — leadership, ownership and decision-making under pressure.', dur:600, tlbl:'SJT',
    qs:[
      { text:"You are the sole associate on the floor during a peak weekend rush. Six customers arrive simultaneously. Your monthly target requires four more bookings in five days. Two customers appear highly likely to commit today. How do you allocate your time?",
        opts:["Prioritise the two high-intent customers with focused attention while briefly acknowledging the others and collecting contact details for immediate follow-up.","Give all six customers precisely equal time — you cannot risk any perception of bias.","Focus exclusively on the two high-intent customers and let the others browse independently.","Call a colleague from an adjacent unit to take over the floor, even though it means handing over the commission."]},
      { text:"A peer consistently receives better walk-in assignments because he arrives 30 minutes early and builds rapport with the floor supervisor. You believe the allocation is unfair. What is your best response?",
        opts:["Adopt what works — arrive earlier and build your own rapport — and if the imbalance persists, raise it with your supervisor using assignment data rather than as a complaint.","Accept it quietly; challenging relationship dynamics in any workplace costs more than it gains.","Report the pattern to HR as favouritism so it is formally on record.","Match him by staying late instead, and mention the unfairness to other trainees so the concern is widely known."]},
      { text:"In your performance review your supervisor praises your target achievement but says your communication with senior management is 'too direct and could be read as aggressive.' You genuinely disagree. What is the most constructive response?",
        opts:["Thank them, ask for one or two specific examples, reflect honestly, and adapt your delivery while keeping the substance of your points.","Accept immediately and soften your communication everywhere to avoid any further friction.","Disagree politely with a counter-example — you should not change your style based on someone's perception.","Ask for the feedback to be reviewed by a second supervisor before you act on it."]},
      { text:"Your Regional Head asks you, as a trainee, to submit customer-experience improvement ideas within 48 hours for direct presentation to senior leadership. You have strong ideas but feel two days is too short to validate them. What do you do?",
        opts:["Submit three or four well-reasoned ideas within 48 hours, stating your assumptions clearly and offering to validate them next — the ask was for ideas, not a finished strategy.","Request a one-week extension so you can gather supporting data before anything reaches senior leadership.","Submit only your single strongest idea — one solid proposal beats four untested ones.","Ask two fellow trainees to co-author a joint submission overnight so the volume looks impressive."]},
      { text:"You discover a data-entry error you made three weeks ago that inflated your brand's monthly unit count by six units, affecting last month's team achievement and your own evaluation. No one has noticed. What is the best action?",
        opts:["Correct the record immediately, inform your supervisor with full transparency, and accept whatever evaluation adjustment follows.","Correct the record quietly in the system and make sure it never happens again — no need to reopen an old month.","Wait for the next audit to surface it; self-reporting an old error only invites scrutiny.","Ask a peer privately whether reporting it is likely to be held against you before deciding."]},
      { text:"A customer insists on a discount well beyond your approved limit and says a competing dealership has already agreed to it. You need the booking to hit target. How do you respond?",
        opts:["Explain the discount limit honestly, build value through approved offers and service benefits, and escalate for exception approval only if there is a genuine business case.","Verbally agree to the discount now and work out later how to get it approved.","Tell the customer the competitor's offer is not credible and hold firm on list price.","Match the number informally by promising free accessories you have not been authorised to give."]},
      { text:"A customer's delivery is delayed because of a documentation lapse in another department. The customer is angry and standing in front of you. What is the best response?",
        opts:["Own the conversation, apologise for the experience, get a verified revised timeline from the department, share it clearly, and follow through personally until delivery.","Explain that the delay was caused by another department so the customer understands it was not your fault.","Give the customer the other department's contact so they can follow up directly.","Promise the earliest date you hope is achievable to calm the customer down now."]},
      { text:"A colleague asks you to log a walk-in he handled under your login because he has already breached a process limit for the month. He says it helps you both. What do you do?",
        opts:["Decline, explain that records have to reflect what actually happened, and offer to help him in ways that do not misstate the data.","Agree once — it is a small adjustment and it genuinely helps a colleague.","Refuse and immediately report the request to the supervisor without speaking to him.","Agree but keep a private note of the arrangement in case it is questioned later."]},
      { text:"You overhear a colleague telling a customer that a warranty covers something you are fairly certain it does not. The sale is about to close. What is your best course of action?",
        opts:["Step in politely to clarify the coverage before the customer commits, then discuss it with the colleague afterwards.","Say nothing now and raise it with your supervisor after the customer has left.","Say nothing at all — you may have misheard, and it is not your sale.","Interrupt and tell the customer in front of your colleague that he has been misinformed."]},
      { text:"Two supervisors give you conflicting instructions on the same afternoon, each treating their task as top priority. Both are senior to you. What do you do?",
        opts:["Tell both openly about the conflict, propose a sequence with your reasoning and time estimates, and ask them to confirm the priority.","Do the task from the more senior supervisor first and explain the delay to the other later.","Attempt both simultaneously and hope you can complete each acceptably.","Ask a peer who has faced this before and follow whatever they did."]},
      { text:"As a trainee you are assigned two weeks of repetitive back-office data cleaning that seems far below the role you were hired for. How do you handle it?",
        opts:["Complete it reliably, look for ways to make it faster and more accurate, and share what the data reveals about the business with your supervisor.","Complete the minimum required and ask to be reassigned to customer-facing work.","Ask your batch mates to share the load so it finishes quickly.","Do it, but make clear to your supervisor that the assignment underuses your qualification."]},
      { text:"A customer offers to pay part of the vehicle cost in cash outside the invoice in exchange for a lower on-road price, and asks you to keep it between the two of you. What do you do?",
        opts:["Decline clearly, explain that the full transaction must be invoiced, and outline the legitimate financing and offer options available.","Decline the cash but let the customer discuss it with someone more senior.","Accept, since the customer is the one taking the compliance risk.","Say you will check and then avoid the topic in the hope the customer drops it."]},
      { text:"With three days left in the month the team is short of target. Your supervisor suggests recording bookings for customers who have shown interest but have not yet committed, to be reversed next month if needed. What is your best response?",
        opts:["Raise your concern that recording uncommitted bookings misstates performance, and propose concrete alternatives — follow-up calls on live quotes, referral outreach, an exchange push — to close the gap genuinely.","Comply because a supervisor has authorised it and the correction is planned anyway.","Refuse quietly and simply avoid entering any of the bookings yourself.","Report the suggestion directly to the Regional Head the same day."]},
      { text:"You have had your worst week — no bookings, two customers lost to competitors — and you are beginning to doubt whether you fit this role. What is the most productive response?",
        opts:["Review your own funnel data to find where conversations are breaking down, ask a strong performer to observe one interaction, and change one specific behaviour this week.","Put in longer hours next week and rely on effort to correct the trend.","Ask your supervisor to reassign you to a segment where conversion is easier.","Accept that some weeks are simply poor and wait for the cycle to turn."]},
      { text:"A customer complaint spans sales and service, and the service advisor blames your paperwork while you believe the fault is in workshop scheduling. The customer is waiting for an answer. What do you do?",
        opts:["Sit with the service advisor, establish the facts together, agree one corrective plan, and give the customer a single consistent response.","Give the customer your version and let the service team give theirs.","Escalate to both department heads and wait for a ruling before responding.","Accept the blame publicly to close the matter quickly and protect the customer relationship."]},
      { text:"You accidentally overhear two senior managers discussing an unannounced restructuring that will affect several colleagues. What is the appropriate action?",
        opts:["Treat it as confidential and say nothing to anyone.","Quietly warn the colleague you are closest to so they can prepare.","Ask one of the managers directly for confirmation so you know how to plan.","Mention it vaguely to your batch so people are not caught unprepared."]},
      { text:"A fellow trainee is falling behind and struggling visibly. You are both being evaluated for the same limited number of pre-placement offers. What do you do?",
        opts:["Help where you genuinely can while keeping your own performance strong — coaching and collaboration are visible in evaluations, and helping one peer does not cost you your own results.","Focus purely on your own numbers; the evaluation is competitive by design.","Help extensively, even if your own targets slip, because teamwork matters more.","Point the peer to your supervisor for support and stay out of it."]}
    ]},
  { id:'logical', name:'Logical Reasoning', icon:'🧩', desc:'17 questions in 10 minutes — deduction, series, spatial logic and argument analysis.', dur:600, tlbl:'Logical',
    qs:[
      { text:"All compliant suppliers ship within 5 days. Supplier Delta ships within 5 days. Which conclusion is valid?",
        opts:["Supplier Delta is definitely compliant.","Supplier Delta is not compliant.","Supplier Delta may or may not be compliant — the premises never state that every 5-day shipper is compliant.","Supplier Delta ships faster than the average compliant supplier."]},
      { text:"Blueprint is to Architect as Score is to Composer. Which pair best mirrors this relationship?",
        opts:["Prescription : Pharmacist","Prescription : Physician","Diagnosis : Patient","Verdict : Barrister"]},
      { text:"Six analysts — Aarav, Bina, Chirag, Divya, Esha and Farhan — finished a task in a strict order with no ties. Chirag finished immediately before Divya. Esha finished immediately after Divya. Aarav finished sometime before Chirag. Bina finished before Aarav. Farhan finished last. Who finished FIRST?",
        opts:["Aarav","Bina","Chirag","Divya"]},
      { text:"Identify the CRITICAL UNSTATED ASSUMPTION: 'Customer satisfaction scores dropped 13 points in the four months since the new trainee batch joined. The trainees clearly need more product training, so we should delay the next deployment.'",
        opts:["The satisfaction score before the batch joined was the historical peak.","Satisfaction scores are the most reliable measure of performance.","The next trainee batch has exactly the same training gaps as this one.","The batch's arrival is the primary cause of the decline, rather than any other factor in the same period."]},
      { text:"Five vehicles occupy bays 1 to 5, left to right. The white car is immediately right of the red car. The black car is at one end. The blue car is in bay 3. The silver car is immediately left of the black car. Which bay holds the red car?",
        opts:["Bay 1","Bay 2","Bay 4","Bay 5"]},
      { text:"Rohit says, 'Anaya's father is the only son of my mother's father.' How is Rohit related to Anaya?",
        opts:["Rohit is Anaya's brother.","Rohit is Anaya's maternal uncle.","Rohit is Anaya's cousin — Anaya's father is Rohit's maternal uncle.","Rohit is Anaya's nephew."]},
      { text:"In a certain code SERVICE is written as UGTXKEG. Using the same code, how is PARTS written?",
        opts:["QBSUT","RCTVU","RCSVU","TCVVW"]},
      { text:"A field executive drives 8 km north, then 6 km east, then 4 km south, then 6 km west. How far is she from her starting point and in which direction?",
        opts:["2 km north","10 km north-east","4 km north","6 km east"]},
      { text:"What comes next in this series?\n\n2, 6, 12, 20, 30, 42, ?",
        opts:["54","56","58","60"]},
      { text:"'Showrooms that added a dedicated EV specialist recorded 20% higher EV sales, so every showroom should hire one.' Which finding would MOST weaken this reasoning?",
        opts:["The showrooms that added a specialist were already the ones with the highest existing EV footfall and enquiry volume.","EV specialists are more expensive to hire than general sales advisors.","Two showrooms with specialists recorded only 14% higher EV sales.","EV sales grew across the industry during the same period."]},
      { text:"In a batch of 120 trainees, 74 speak Hindi, 62 speak Tamil, and 20 speak neither. How many speak both languages?",
        opts:["16","24","36","46"]},
      { text:"Statements: No trainee who missed the induction received the field kit. Some trainees who received the field kit were assigned to the East zone.\n\nConclusions: I. Some East-zone trainees attended the induction. II. All trainees who missed the induction were assigned outside the East zone.",
        opts:["Only conclusion II follows.","Only conclusion I follows.","Both conclusions follow.","Neither conclusion follows."]},
      { text:"A cube painted on all six outer faces is cut into 64 identical smaller cubes. How many of the small cubes have exactly two painted faces?",
        opts:["16","24","32","8"]},
      { text:"If the 1st of a month falls on a Saturday, what day is the 25th of the same month?",
        opts:["Monday","Tuesday","Wednesday","Thursday"]},
      { text:"Three trainees are questioned about a missing file, and exactly ONE of them is lying.\n\nA says: 'B took it.'\nB says: 'I did not take it.'\nC says: 'A took it.'\n\nWho took the file?",
        opts:["A took the file.","B took the file.","C took the file.","It cannot be determined."]},
      { text:"Some managers are engineers. All engineers are graduates. Which statement MUST be true?",
        opts:["All managers are graduates.","All graduates are managers.","No engineer is a manager.","Some managers are graduates."]},
      { text:"A policy states: 'If a test drive is booked, a valid licence must be recorded. If a valid licence is not recorded, the booking is auto-cancelled.' A particular booking was NOT auto-cancelled. What is logically guaranteed?",
        opts:["A test drive was definitely booked.","No test drive was booked.","A valid licence was recorded.","The licence was verified manually by a supervisor."]}
    ]},
  { id:'numerical', name:'Numerical Reasoning', icon:'📊', desc:'17 questions in 10 minutes — data interpretation, percentages, ratios and P&L analysis.', dur:600, tlbl:'Numerical',
    qs:[
      { text:"Quarterly unit sales are shown below. Which product line recorded the highest ABSOLUTE growth from Q2 to Q4?",
        table:{ hdrs:['Product Line','Q2','Q3','Q4'], rows:[['Alpha EV','44','52','71'],['Beta Hybrid','28','31','38'],['Gamma ICE','61','58','74'],['Delta EV','112','119','138'],['Epsilon Hybrid','39','43','49'],['Zeta EV','33','29','44']] },
        opts:["Delta EV — 26 units","Alpha EV — 27 units","Gamma ICE — 13 units","Zeta EV — 11 units"]},
      { text:"A showroom's monthly funnel: 560 walk-ins. Walk-in to test-drive 42%, test-drive to quote 35%, quote to booking 31%, booking to delivery 96%. How many deliveries in the month, to the nearest whole vehicle?",
        opts:["21 deliveries","24 deliveries","28 deliveries","19 deliveries"]},
      { text:"A showroom's monthly fixed cost is ₹18.5L. Average gross margin per vehicle sold is ₹1.20L, and after-sales margin is ₹8,000 per vehicle serviced. In May it sold 16 vehicles and serviced 75. What is May's operating profit or loss?",
        opts:["Profit of ₹6,70,000","Profit of ₹4,30,000","Loss of ₹1,30,000","Profit of ₹5,50,000"]},
      { text:"In FY25 the EV division was 26% of total volume of 5,200 units. For FY26, EV volume is forecast to grow 44% and total volume 15%. What will the EV share of total volume be in FY26?",
        opts:["29.9%","32.6%","35.2%","27.6%"]},
      { text:"Branch performance for last month is shown below. Which branch had the highest walk-in to booking conversion rate?",
        table:{ hdrs:['Branch','Walk-ins','Bookings','Revenue (₹L)'], rows:[['North','480','72','86.4'],['South','350','63','81.9'],['East','610','73','94.9'],['West','290','58','72.5']] },
        opts:["South — 18.0%","West — 20.0%","North — 15.0%","East — 12.0%"]},
      { text:"Using the model-wise data below, which model generated the highest NET revenue after discount?",
        table:{ hdrs:['Model','Units','Unit Price (₹L)','Discount %'], rows:[['Model A','40','8.50','4'],['Model B','25','12.00','6'],['Model C','18','15.50','3'],['Model D','30','6.80','8']] },
        opts:["Model B — ₹282.0L","Model C — ₹270.6L","Model A — ₹326.4L","Model D — ₹187.7L"]},
      { text:"A model's price is increased by 20% and then reduced by 20%. What is the net change from the original price?",
        opts:["No net change","A 4% decrease","A 4% increase","A 2% decrease"]},
      { text:"Petrol, diesel and EV units are sold in the ratio 5 : 3 : 2. If 240 EV units were sold, how many petrol units were sold?",
        opts:["600","400","480","720"]},
      { text:"A customer takes a ₹6,00,000 vehicle loan at 9% simple interest for 3 years. What is the total interest payable?",
        opts:["₹54,000","₹1,62,000","₹1,80,000","₹2,16,000"]},
      { text:"Five advisors averaged 12 units each last month. A sixth advisor who sold 24 units is added to the team's figures. What is the new average?",
        opts:["14 units","13 units","15 units","18 units"]},
      { text:"Of 200 surveyed customers, 60% gave a rating of 4.5 and the remaining 40% gave 3.5. What is the overall average rating?",
        opts:["4.0","4.1","4.2","3.9"]},
      { text:"A showroom's fixed monthly cost is ₹12L and the contribution per vehicle sold is ₹75,000. How many vehicles must it sell to break even?",
        opts:["16 vehicles","15 vehicles","18 vehicles","20 vehicles"]},
      { text:"An advisor's monthly target is 45 units and she delivers 36. What percentage of target was achieved, and what was the shortfall?",
        opts:["75% achieved; 25% shortfall","82% achieved; 18% shortfall","80% achieved; 20% shortfall","90% achieved; 10% shortfall"]},
      { text:"Annual sales of 500 units grow 10% in year 1 and a further 20% in year 2. What is the volume at the end of year 2?",
        opts:["650 units","660 units","665 units","680 units"]},
      { text:"One service bay completes 6 jobs per day. If three more identical bays are added, how many working days are needed to complete 240 jobs?",
        opts:["10 days","12 days","8 days","15 days"]},
      { text:"A vehicle costs the dealer ₹7,20,000 and is listed at ₹8,40,000. A discount of ₹30,000 is given. What is the gross margin as a percentage of the selling price?",
        opts:["10.7%","12.5%","14.3%","11.1%"]},
      { text:"A test-drive fleet covers 4,200 km in a month at an average efficiency of 14 km per litre. Fuel costs ₹105 per litre. What is the monthly fuel cost?",
        opts:["₹31,500","₹29,400","₹33,600","₹42,000"]}
    ]},
  { id:'verbal', name:'Verbal Reasoning', icon:'📝', desc:'17 questions in 10 minutes — critical reading, inference, assumption and precision of language.', dur:600, tlbl:'Verbal',
    qs:[
      { text:"'All showrooms that exceeded quarterly targets received the Excellence Award. The City Centre showroom received the Excellence Award. Therefore the City Centre showroom exceeded its quarterly target.'\n\nEvaluate this argument.",
        opts:["Valid — the premises guarantee the conclusion.","Invalid — it affirms the consequent; the award may also be granted for reasons other than exceeding targets.","Invalid — the sample size is too small to support any conclusion.","Valid — awards are given only when quarterly targets are exceeded."]},
      { text:"A Regional Head proposes closing a low-revenue, high-rent showroom and moving its staff to a new high-footfall mega-showroom. Which single statement MOST STRONGLY supports the proposal?",
        opts:["Three other dealership groups in the state consolidated their operations in the last two years.","The existing showroom has missed its target in three of the last four quarters.","Rent at the existing location is 40% above the portfolio average per square foot.","The proposed location has the city's highest per-capita premium-vehicle purchases and three times the footfall, and internal modelling shows consolidated showrooms average 22% lower cost per sale."]},
      { text:"Which statement is NOT a fact — it is an inference or opinion?\n\n'Organisation X was founded in this city and now operates 18 outlets across two states. Its EV portfolio grew 44% in FY25 — making it undeniably the most future-ready dealership group in the region.'",
        opts:["Organisation X was founded in this city.","Organisation X operates 18 outlets across two states.","Organisation X is undeniably the most future-ready dealership group in the region.","Organisation X's EV portfolio grew 44% in FY25."]},
      { text:"A report concludes: 'Because average response time improved by 12%, customer experience has unquestionably improved.' What is the primary logical weakness?",
        opts:["Response time is only one dimension of customer experience; other dimensions may have worsened, so a gain in one metric does not establish overall improvement.","A 12% improvement is too small to matter in practice.","The word 'unquestionably' is too strong for any empirical finding.","Response time has no relationship at all with customer satisfaction."]},
      { text:"In the sentence 'The manager's terse reply ended the discussion,' the word 'terse' most nearly means:",
        opts:["Angry and loud","Polite and detailed","Curt and brief","Hesitant and unclear"]},
      { text:"After a service centre extended its weekend hours, appointment no-shows fell 18%, total appointments rose 9%, and staff overtime cost rose 22%.\n\nWhich inference is BEST supported?",
        opts:["Extended weekend hours are unprofitable for the service centre.","The extension coincided with better appointment adherence and higher volume, at a higher labour cost.","Customers prefer weekend service to weekday service.","No-shows fell because customers were charged for missed appointments."]},
      { text:"Choose the option that most logically completes the argument.\n\n'A new digital booking tool cut average booking time from 14 minutes to 6 minutes, yet satisfaction with the booking process did not improve. This suggests that ___'",
        opts:["the tool must be technically faulty.","customers dislike digital tools in general.","satisfaction surveys are unreliable measures.","speed was not the main driver of customers' dissatisfaction with the booking process."]},
      { text:"'We should stop offering evening test drives — only 8% of them convert into bookings.'\n\nWhich assumption does this argument REQUIRE?",
        opts:["Evening test drives cost more to staff than daytime test drives.","Immediate conversion rate adequately captures the value of an evening test drive — they contribute little that converts later.","Customers who take evening test drives are less serious buyers.","Daytime test drives are always fully booked."]},
      { text:"'Enquiries that receive a follow-up call within 24 hours book at twice the rate of those called later, so calling every enquiry within 24 hours would double our bookings.'\n\nWhich finding would MOST weaken this reasoning?",
        opts:["Some advisors record their call times inaccurately.","The follow-up call script was revised last quarter.","Advisors already choose the most interested enquiries to call first, so fast calls and high buyer intent occur together.","A minority of customers dislike receiving follow-up calls."]},
      { text:"Passage:\n\nEV enquiries at the group's outlets tripled over two years, yet conversion stayed flat. Post-enquiry interviews suggest the gap is not price but confidence: buyers are unsure about charging access on intercity routes and about battery replacement cost after five years. Outlets that began publishing local charging maps and written battery-warranty explainers converted noticeably better than those that did not.\n\nWhat is the main point of the passage?",
        opts:["EV conversion is limited mainly by buyer uncertainty, which better information at the outlet can reduce.","EV enquiries tripled across the group's outlets in two years.","EV prices must fall before conversion can improve.","Battery warranties should be extended to ten years."]},
      { text:"A report states: 'Every advisor who exceeded target received a bonus. Advisor R received a bonus but did not exceed target.'\n\nWhich statement resolves this without any contradiction?",
        opts:["The report must contain an error — R cannot have received a bonus.","Bonuses may also be awarded for reasons other than exceeding target.","R must have exceeded target without it being recorded.","Only advisors who exceed target are eligible for a bonus."]},
      { text:"Which sentence is grammatically correct?",
        opts:["Neither of the two showrooms have met their targets.","The report, along with the annexures, were circulated yesterday.","Neither of the two showrooms has met its target.","Each of the advisors were given their own leads list."]},
      { text:"Choose the pair that best completes the sentence.\n\n'Although the proposal was ______ in scope, its execution plan was surprisingly ______.'",
        opts:["ambitious … modest","narrow … limited","detailed … thorough","vague … unclear"]},
      { text:"Identify the reasoning flaw: 'Either we cut prices by 10% this month or we lose the entire quarter.'",
        opts:["Circular reasoning — the conclusion simply restates the premise.","False dilemma — it presents two options as though no others exist.","Appeal to authority — it relies on an unnamed expert.","Hasty generalisation — it draws on far too few cases."]},
      { text:"Paragraph:\n\nThe group's used-vehicle business grew 34% in units, but margin per unit fell from ₹41,000 to ₹28,000, largely because its own procurement teams competed for the same limited stock and bid prices up. Total used-vehicle profit therefore rose only marginally despite the volume jump.\n\nWhich sentence best summarises the paragraph?",
        opts:["The used-vehicle business grew 34% in units last year.","Procurement teams should stop bidding against one another.","Strong unit growth in used vehicles was largely offset by thinner margins caused by internal procurement competition.","Used-vehicle margin fell from ₹41,000 to ₹28,000 per unit."]},
      { text:"'Almost every customer who used the courtesy-vehicle facility rated the service five stars. Only 12% of customers were offered the facility.'\n\nWhich conclusion does NOT follow?",
        opts:["Most customers were not offered the courtesy-vehicle facility.","Customers who used the facility rated the service highly.","The ratings given by the other 88% of customers are not described here.","The courtesy-vehicle facility is the main reason for the service centre's overall rating."]},
      { text:"Which rewrite most accurately preserves the meaning of this sentence?\n\n'Sales rose in most months, though the annual total fell slightly.'",
        opts:["Sales increased in a majority of months, yet the year's total was marginally lower.","Sales increased every month, but the annual total dropped sharply.","Sales fell in most months, and the annual total fell as well.","Sales were flat through the year and the annual total was unchanged."]}
    ]},
  { id:'game', name:'Cognitive Agility', icon:'🧠', desc:'Eight high-pressure cognitive challenges — memory, mental math, and hard puzzles under tight time.', dur:480, tlbl:'Game', isGame:true,
    qs:[
      { text:"Pattern Memory — Hard Mode", gameType:'patternmem', opts:["Done"] },
      { text:"Math Blitz — Hard Mode", gameType:'mathblitz', opts:["Play"] },
      { text:"Identify the rule governing this sequence and select the next term.\n\n3 → 7 → 16 → 35 → 74 → ?",
        seq:true, seqLabels:['T1','T2','T3','T4','T5','T6'],
        seqVals:['3','7','16','35','74','?'],
        opts:["148","151","153","157"]},
      { text:"What is the angle between the hour hand and the minute hand at exactly 8:23?",
        fig:'<svg viewBox="0 0 200 200" width="180" height="180" xmlns="http://www.w3.org/2000/svg"><circle cx="100" cy="100" r="88" fill="none" stroke="#888" stroke-width="3"/>'+
          [0,1,2,3,4,5,6,7,8,9,10,11].map(n=>{const a=(n*30-90)*Math.PI/180;const x1=100+78*Math.cos(a),y1=100+78*Math.sin(a),x2=100+88*Math.cos(a),y2=100+88*Math.sin(a);return '<line x1="'+x1.toFixed(1)+'" y1="'+y1.toFixed(1)+'" x2="'+x2.toFixed(1)+'" y2="'+y2.toFixed(1)+'" stroke="#aaa" stroke-width="2"/>';}).join('')+
          [12,3,6,9].map((lab,i)=>{const ang=(i*90-90)*Math.PI/180;const x=100+64*Math.cos(ang),y=100+64*Math.sin(ang);return '<text x="'+x.toFixed(1)+'" y="'+(y+5).toFixed(1)+'" fill="#d4a843" font-size="16" font-family="sans-serif" text-anchor="middle" font-weight="700">'+lab+'</text>';}).join('')+
          '<line x1="100" y1="100" x2="58.3" y2="114.0" stroke="#fff" stroke-width="4" stroke-linecap="round"/>'+
          '<line x1="100" y1="100" x2="141.5" y2="146.1" stroke="#d4a843" stroke-width="5" stroke-linecap="round"/>'+
          '<circle cx="100" cy="100" r="5" fill="#d4a843"/></svg>',
        opts:["113.5°","118.5°","106.5°","121.0°"]},
      { text:"How many triangles of any size are there in the figure below?",
        fig:'<svg viewBox="0 0 220 180" width="220" height="180" xmlns="http://www.w3.org/2000/svg"><polygon points="110,20 200,160 20,160" fill="none" stroke="#d4a843" stroke-width="3"/><line x1="110" y1="20" x2="65" y2="160" stroke="#d4a843" stroke-width="2.5"/><line x1="110" y1="20" x2="110" y2="160" stroke="#d4a843" stroke-width="2.5"/><line x1="110" y1="20" x2="155" y2="160" stroke="#d4a843" stroke-width="2.5"/></svg>',
        opts:["8 triangles","9 triangles","10 triangles","12 triangles"]},
      { text:"Which letter continues this series?\n\nB, D, G, K, P, ?",
        opts:["U","V","X","T"]},
      { text:"Study the pattern in the first two rows and find the missing value.",
        table:{ hdrs:['A','B','Result'], rows:[['8','5','39'],['9','4','65'],['11','6','?']] },
        opts:["77","95","85","70"]},
      { text:"Which number does NOT belong with the others?",
        opts:["289","324","361","392"]}
    ]},
  { id:'predictive', name:'Behavioural Profile', icon:'🧬', desc:'17 forced-choice items in 10 minutes — drives, working style and cultural fit. There are no right answers, only honest ones.', dur:600, tlbl:'Behavioural',
    qs:[
      { text:"Which descriptor best captures how you energise yourself at work? Choose the one that feels most naturally true.",
        opts:["I thrive when I can set and chase ambitious goals — forward momentum energises me.","I feel most engaged when I am supporting, mentoring or developing others.","I gain energy from building systems, processes and consistent quality.","I am most alive when collaborating and building trust across teams."]},
      { text:"When a project hits an unexpected obstacle, your instinctive first move is to:",
        opts:["Reframe quickly and push to find a path forward, even an imperfect one.","Consult the people most affected and build agreement before acting.","Pause, map the full problem systematically, then act with precision.","Look for a creative angle that others have not considered."]},
      { text:"In a team setting, the role you naturally gravitate toward is:",
        opts:["The one who sets direction, drives pace and holds the team accountable.","The one who listens carefully and ensures no voice is left out.","The one who organises information and keeps everyone on track.","The one who challenges assumptions and sparks new thinking."]},
      { text:"Your approach to giving feedback is best described as:",
        opts:["Direct and specific — I say what I mean and trust people to handle honesty.","Empathetic first — I understand the person's perspective before sharing.","Structured — I prepare carefully so feedback is balanced and actionable.","Collaborative — I explore the issue together rather than deliver a verdict."]},
      { text:"What motivates you most in a professional environment?",
        opts:["Impact and visible results — I need to see my work making a difference.","Growth and learning — new skills and knowledge drive me.","Recognition and belonging — I want to feel valued and part of something.","Autonomy and mastery — freedom to do excellent work on my own terms."]},
      { text:"When priorities change suddenly and your plan for the week is void, you typically:",
        opts:["Reset the plan quickly and start moving on the new priority the same day.","Check in with the people affected before rebuilding the plan.","Rebuild the plan carefully so nothing already committed is dropped.","Treat it as a chance to try a different approach altogether."]},
      { text:"How do you prefer to make a decision when the data is incomplete?",
        opts:["Decide with the best available information and correct course as I learn.","Seek input from those with experience before committing.","Wait until I can gather one more layer of evidence.","Test a small version of the decision first and read the result."]},
      { text:"Under sustained pressure, the behaviour most characteristic of you is:",
        opts:["I raise my intensity and drive harder toward the outcome.","I check on how the team is coping and steady the group.","I become more methodical and reduce the risk of error.","I look for a shortcut or a smarter route through the problem."]},
      { text:"You are most satisfied at the end of a working day when:",
        opts:["I have moved a difficult number, deal or target forward.","Someone I helped made progress because of it.","Everything I owned was completed accurately and on time.","I solved something in a way nobody had tried before."]},
      { text:"When you disagree with a decision made by someone senior, you usually:",
        opts:["Say so directly, with my reasoning, and then commit fully to whatever is decided.","Raise it privately and gently to avoid putting anyone on the spot.","Prepare a written case with evidence before responding.","Ask questions that surface the assumption I think is wrong."]},
      { text:"Your relationship with rules and established processes is best described as:",
        opts:["I follow them, but I will challenge a process that is clearly blocking results.","I follow them and help others do the same — consistency protects the team.","I follow them precisely; process exists for good reasons.","I follow the intent and look for better ways to achieve the same outcome."]},
      { text:"When you join a new team, your first instinct is to:",
        opts:["Find out how success is measured and start contributing to it immediately.","Get to know the people and understand how the team works together.","Learn the systems, data and processes end to end before acting.","Look for what is being done inefficiently and where I could add something new."]},
      { text:"How do you respond to a target you privately believe is unrealistic?",
        opts:["Commit to it, state the risks openly, and chase it as hard as I can.","Discuss it with the team so we plan around it together.","Model the numbers to show exactly where the gap lies before responding.","Look for an unconventional route that makes the number possible."]},
      { text:"The kind of recognition that means the most to you is:",
        opts:["Being trusted with a bigger target or a harder problem.","Being told I made someone's work or day genuinely better.","Being known as the person whose work is always reliable.","Being credited for an idea that changed how something is done."]},
      { text:"When you make a visible mistake, your natural response is to:",
        opts:["Own it immediately, fix it fast, and share what I changed so it does not recur.","Tell the people affected first and make it right for them.","Analyse how it happened and put a check in place.","Reframe it as a learning input and adjust my approach."]},
      { text:"Which working environment brings out your best performance?",
        opts:["Fast-moving, target-driven, with clear ownership and visible scoreboards.","Supportive and people-centred, with strong relationships across the team.","Well-structured and predictable, with clear standards and processes.","Open and exploratory, where trying new approaches is encouraged."]},
      { text:"Five years from now, the outcome you would consider a real success is:",
        opts:["Owning a business unit and being accountable for its numbers.","Having built and developed a team that people want to join.","Being the person the organisation relies on to get things right.","Having launched something in the business that did not exist before."]}
    ]}
];

export const ROUND_NAMES = ['SJT','Logical','Numerical','Verbal','Game','Behavioural'];

export const CORRECT_ANS = [
  // SJT — best answer authored at index 0 for every item (17)
  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
  // Logical (17)
  [2,1,1,3,0,2,1,2,1,0,2,1,1,1,0,3,2],
  // Numerical (17)
  [1,1,0,1,1,2,1,0,1,0,1,0,2,1,0,3,0],
  // Verbal (17)
  [1,3,2,0,2,1,3,1,2,0,1,2,0,1,2,3,0],
  // Game (8) — patternmem, mathblitz, then six hard puzzles
  [0,0,2,0,2,1,2,3],
  // Behavioural — forced-choice profile, index 0 scored as the drive-led response (17)
  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
];
